language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm run install-dep
before_script: npm run clean && npm run validate
script:  
  - if [ -n "$ARTIFACTORY_URL" ]; then npm run deploy; fi
  - git fetch --unshallow && npm run sonarqube

notifications:
  email: false
  webhooks:
    - secure: "budeUSiGUDWhJJq1S76l3SvgQ75p384TCwXdbDK15uoRfOfM1QtWNXR1MrGSLAQSy7uXTYJ8UuRiPw9uFLCwf7LxKCQRq8PTDq0FC/m78/LGTQIvoG3KBrDyHdiqdj0hmnGY9JmL5Oed+5f/tuvrkyJrHDT6PTp7/dlSC/VLYtGOer7nuJV1bmobqSdJapHc1KvuXOn8Im5773mhPOYlb4jCOKQYKrULExZzmarCBh0Sl1ytGY0NK7apwnTGRcgrAQRH45TvZwh+3mCRVkaGHKYCGfutno9MlOYURKwXtKx8hckZPuAkh3mwRUmGA+oBTi2yzQk/xQ430Uhy3jFf1gAuk5CSlZx4glBdaEmlusfgwJAG88nBB4HdzG1BC5yKwPRALXXZ4uPmC80wH0a7tG8xz1OQF7YOTzQB6OTJMTzn2Wgp1fncDSx0m+vVPSsDwEJqrDJrkQ9g0GU6UJkBfEq7POE9JdJwyUUAUFAx5C3uNtq7zv3B7oaCLY78WeJnnzHN2Pa03+SrVN3pjexhPrVzluUQ7QWCdaQaBK0ylJfdon+RiCHTGiJ4695O4AgjTqf/uctDlWzut7rPqpN1MZG5ggTawvEaeUQUCva50plKw/C9FGQV4lu5RLEyPNU8PlW68Z/IcOdJLiNXXn/WH7SrBWPz1k1X+6KpUEh1W4Y="
  on_start: always

