name: sonar-release
# This workflow is triggered when publishing a new github release
on: 
  release:
    types:
      - published
  
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Configure AWS Credentials # Required for pushing the binaries
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BINARIES_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BINARIES_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.BINARIES_AWS_REGION }}
      - name: Release
        id: release
        uses: SonarSource/gh-action_release/main@v4
        with:
          publish_to_binaries: true # optional, default: true
          slack_channel: team-sc-azdo-extension-release-notif
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
          BINARIES_AWS_DEPLOY: ${{ secrets.BINARIES_AWS_DEPLOY }} # Required for pushing the binaries
          BURGRX_USER: ${{ secrets.BURGRX_USER }}
          BURGRX_PASSWORD: ${{ secrets.BURGRX_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          SLACK_API_TOKEN: ${{secrets.SLACK_API_TOKEN }}
      - name: Release action results
        if: always()
        run: |
          echo "${{ steps.release.outputs.releasability }}"
          echo "${{ steps.release.outputs.promote }}"
          echo "${{ steps.release.outputs.publish_to_binaries }}"
          echo "${{ steps.release.outputs.release }}"
