name: sonar-release
# This workflow is triggered when publishing a new github release
on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v5
    with:
      publishToBinaries: true
      slackChannel: squad-analysis-experience-azdo
